"use strict";
let myName = document.getElementById('name');
let desig = document.getElementById('designation');
let phone = document.getElementById('phone');
let email = document.getElementById('email');
let DOB = document.getElementById('dob');
let address = document.getElementById('Address');
let pic = document.getElementById('pic');
let pass = document.getElementById('pass');
let degree = document.getElementById('deg');
let institute = document.getElementById('uni');
let pass1 = document.getElementById('pass1');
let degree1 = document.getElementById('deg1');
let institute1 = document.getElementById('uni1');
let skill1 = document.getElementById('skill1');
let skill2 = document.getElementById('skill2');
let skill3 = document.getElementById('skill3');
let skill4 = document.getElementById('skill4');
let skill5 = document.getElementById('skill5');
let skill6 = document.getElementById('skill6');
let skill7 = document.getElementById('skill7');
let skill8 = document.getElementById('skill8');
let lang = document.getElementById('lang');
let lang1 = document.getElementById('lang1');
let lang2 = document.getElementById('lang2');
let styear = document.getElementById('styear');
let endyear = document.getElementById('endyear');
let company = document.getElementById('company');
let jobTitle = document.getElementById('jobTitle');
let styear1 = document.getElementById('styear1');
let endyear1 = document.getElementById('endyear1');
let company1 = document.getElementById('company1');
let jobTitle1 = document.getElementById('jobTitle1');
let link = document.getElementById('link');
let link1 = document.getElementById('link1');
let submitBtn = document.getElementById('submitBtn');
let form = document.getElementById('form');
form?.addEventListener('submit', (e) => {
    e.preventDefault();
    localStorage.setItem('name', myName.value);
    localStorage.setItem('designation', desig.value);
    localStorage.setItem('phone', phone.value);
    localStorage.setItem('email', email.value);
    localStorage.setItem('dob', DOB.value);
    localStorage.setItem('Address', address.value);
    localStorage.setItem('pass', pass.value);
    localStorage.setItem('deg', degree.value);
    localStorage.setItem('uni', institute.value);
    localStorage.setItem('pass1', pass1.value);
    localStorage.setItem('deg1', degree1.value);
    localStorage.setItem('uni1', institute1.value);
    localStorage.setItem('skill1', skill1.value);
    localStorage.setItem('skill2', skill2.value);
    localStorage.setItem('skill3', skill3.value);
    localStorage.setItem('skill4', skill4.value);
    localStorage.setItem('skill5', skill5.value);
    localStorage.setItem('skill6', skill6.value);
    localStorage.setItem('skill7', skill7.value);
    localStorage.setItem('skill8', skill8.value);
    localStorage.setItem('lang', lang.value);
    localStorage.setItem('lang1', lang1.value);
    localStorage.setItem('lang2', lang2.value);
    localStorage.setItem('styear', styear.value);
    localStorage.setItem('endyear', endyear.value);
    localStorage.setItem('company', company.value);
    localStorage.setItem('jobTitle', jobTitle.value);
    localStorage.setItem('styear1', styear1.value);
    localStorage.setItem('endyear1', endyear1.value);
    localStorage.setItem('company1', company1.value);
    localStorage.setItem('jobTitle1', jobTitle1.value);
    localStorage.setItem('link', link.value);
    localStorage.setItem('link1', link1.value);
    console.log(pic.files[0]);
    if (pic.files && pic.files[0]) {
        let reader = new FileReader();
        reader.addEventListener("load", () => {
            let textImg = reader.result;
            localStorage.setItem('profile_pic', textImg);
        });
        reader.readAsDataURL(pic.files[0]);
    }
    window.location.href = 'resume/static.html';
});
